version: '3.8'
services:
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  user-service:
    build: .
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/user_service
      PORT: 5000
    env_file:
      - .env

volumes:
  mongo-data: